name: Build jellyfin-ffmpeg

on:
  push:
    branches:
      - jellyfin

  pull_request:
    branches:
      - jellyfin

  workflow_dispatch:

jobs:
  build_linux:
    name: Build ${{ matrix.release }} ${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        release:
          # Debian
          - buster
          - bullseye
          # Ubuntu
          - bionic
          - focal
          - hirsute
          - impish
        arch:
          - amd64
          - arm64
          - armhf
        include:
          - release: buster
            docker_release: debian:buster
            gcc_version: 8
          - release: bullseye
            docker_release: debian:bullseye
            gcc_version: 10
          - release: bionic
            docker_release: ubuntu:bionic
            gcc_version: 7
          - release: focal
            docker_release: ubuntu:focal
            gcc_version: 9
          - release: hirsute
            docker_release: ubuntu:hirsute
            gcc_version: 10
          - release: impish
            docker_release: ubuntu:impish
            gcc_version: 11

    steps:
      - uses: actions/checkout@v2

      - name: Install make and mmv
        run: sudo apt-get install make mmv

      - name: Create temporary artifact directory
        run: mkdir -p "/tmp/build_${{ matrix.release }}_${{ matrix.arch }}"

      - name: Prepare Dockerfile
        run: make -f Dockerfile.make DISTRO=${{ matrix.docker_release }} ARCH=${{ matrix.arch }} GCC_VER=${{ matrix.gcc_version }}

      - name: Build Dockerfile
        run: docker build . -t "build_${{ matrix.release }}_${{ matrix.arch }}"

      - name: Run Dockerfile to build archives
        run: docker run --rm -e "RELEASE=${{ matrix.docker_release }}" -v "/tmp/build_${{ matrix.release }}_${{ matrix.arch }}:/dist" "build_${{ matrix.release }}_${{ matrix.arch }}"

      - name: Rename package files
        run: mmv "/tmp/build_${{ matrix.release }}_${{ matrix.arch }}/*_${{ matrix.arch }}.*" "/tmp/build_${{ matrix.release }}_${{ matrix.arch }}/#1-${{ matrix.release }}_${{ matrix.arch }}.#2"

      - name: Upload package artifacts
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ${{ matrix.release }}_${{ matrix.arch }}
          path: /tmp/build_${{ matrix.release }}_${{ matrix.arch }}

  build_win64:
    name: Build windows win64
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Install make
        run: sudo apt-get install make

      - name: Build
        run: ./build-win64 dist

      - name: Upload Packages
        uses: actions/upload-artifact@v2.2.3
        with:
          name: windows_win64
          path: dist
